/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdminsConfigPart from './AdminsConfigPart';
import CFConfigPart from './CFConfigPart';
import CaCertificatesConfigPart from './CaCertificatesConfigPart';
import CacheConfigPart from './CacheConfigPart';
import DefaultConfigPart from './DefaultConfigPart';
import GatewayMessageQueueInfo from './GatewayMessageQueueInfo';
import GeneralConfigPart from './GeneralConfigPart';
import K8SAuthsConfigPart from './K8SAuthsConfigPart';
import KMIPConfigPart from './KMIPConfigPart';
import KerberosConfigPart from './KerberosConfigPart';
import LdapConfigPart from './LdapConfigPart';
import LeadershipConfigPart from './LeadershipConfigPart';
import LogForwardingConfigPart from './LogForwardingConfigPart';
import MigrationsConfigPart from './MigrationsConfigPart';
import ProducersConfigPart from './ProducersConfigPart';
import RotatorsConfigPart from './RotatorsConfigPart';

/**
 * The AkeylessGatewayConfig model module.
 * @module model/AkeylessGatewayConfig
 * @version 5.0.4
 */
class AkeylessGatewayConfig {
    /**
     * Constructs a new <code>AkeylessGatewayConfig</code>.
     * @alias module:model/AkeylessGatewayConfig
     */
    constructor() { 
        
        AkeylessGatewayConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AkeylessGatewayConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AkeylessGatewayConfig} obj Optional instance to populate.
     * @return {module:model/AkeylessGatewayConfig} The populated <code>AkeylessGatewayConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AkeylessGatewayConfig();

            if (data.hasOwnProperty('admins')) {
                obj['admins'] = AdminsConfigPart.constructFromObject(data['admins']);
            }
            if (data.hasOwnProperty('ca_certificates')) {
                obj['ca_certificates'] = CaCertificatesConfigPart.constructFromObject(data['ca_certificates']);
            }
            if (data.hasOwnProperty('cache')) {
                obj['cache'] = CacheConfigPart.constructFromObject(data['cache']);
            }
            if (data.hasOwnProperty('cf')) {
                obj['cf'] = CFConfigPart.constructFromObject(data['cf']);
            }
            if (data.hasOwnProperty('config_protection_key_name')) {
                obj['config_protection_key_name'] = ApiClient.convertToType(data['config_protection_key_name'], 'String');
            }
            if (data.hasOwnProperty('general')) {
                obj['general'] = GeneralConfigPart.constructFromObject(data['general']);
            }
            if (data.hasOwnProperty('k8s_auths')) {
                obj['k8s_auths'] = K8SAuthsConfigPart.constructFromObject(data['k8s_auths']);
            }
            if (data.hasOwnProperty('kerberos')) {
                obj['kerberos'] = KerberosConfigPart.constructFromObject(data['kerberos']);
            }
            if (data.hasOwnProperty('kmip_clients')) {
                obj['kmip_clients'] = KMIPConfigPart.constructFromObject(data['kmip_clients']);
            }
            if (data.hasOwnProperty('ldap')) {
                obj['ldap'] = LdapConfigPart.constructFromObject(data['ldap']);
            }
            if (data.hasOwnProperty('leadership')) {
                obj['leadership'] = LeadershipConfigPart.constructFromObject(data['leadership']);
            }
            if (data.hasOwnProperty('log_forwarding')) {
                obj['log_forwarding'] = LogForwardingConfigPart.constructFromObject(data['log_forwarding']);
            }
            if (data.hasOwnProperty('message_queue_info')) {
                obj['message_queue_info'] = GatewayMessageQueueInfo.constructFromObject(data['message_queue_info']);
            }
            if (data.hasOwnProperty('migrations')) {
                obj['migrations'] = MigrationsConfigPart.constructFromObject(data['migrations']);
            }
            if (data.hasOwnProperty('producers')) {
                obj['producers'] = ProducersConfigPart.constructFromObject(data['producers']);
            }
            if (data.hasOwnProperty('rotators')) {
                obj['rotators'] = RotatorsConfigPart.constructFromObject(data['rotators']);
            }
            if (data.hasOwnProperty('saml')) {
                obj['saml'] = DefaultConfigPart.constructFromObject(data['saml']);
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AkeylessGatewayConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AkeylessGatewayConfig</code>.
     */
    static validateJSON(data) {
        // validate the optional field `admins`
        if (data['admins']) { // data not null
          AdminsConfigPart.validateJSON(data['admins']);
        }
        // validate the optional field `ca_certificates`
        if (data['ca_certificates']) { // data not null
          CaCertificatesConfigPart.validateJSON(data['ca_certificates']);
        }
        // validate the optional field `cache`
        if (data['cache']) { // data not null
          CacheConfigPart.validateJSON(data['cache']);
        }
        // validate the optional field `cf`
        if (data['cf']) { // data not null
          CFConfigPart.validateJSON(data['cf']);
        }
        // ensure the json data is a string
        if (data['config_protection_key_name'] && !(typeof data['config_protection_key_name'] === 'string' || data['config_protection_key_name'] instanceof String)) {
            throw new Error("Expected the field `config_protection_key_name` to be a primitive type in the JSON string but got " + data['config_protection_key_name']);
        }
        // validate the optional field `general`
        if (data['general']) { // data not null
          GeneralConfigPart.validateJSON(data['general']);
        }
        // validate the optional field `k8s_auths`
        if (data['k8s_auths']) { // data not null
          K8SAuthsConfigPart.validateJSON(data['k8s_auths']);
        }
        // validate the optional field `kerberos`
        if (data['kerberos']) { // data not null
          KerberosConfigPart.validateJSON(data['kerberos']);
        }
        // validate the optional field `kmip_clients`
        if (data['kmip_clients']) { // data not null
          KMIPConfigPart.validateJSON(data['kmip_clients']);
        }
        // validate the optional field `ldap`
        if (data['ldap']) { // data not null
          LdapConfigPart.validateJSON(data['ldap']);
        }
        // validate the optional field `leadership`
        if (data['leadership']) { // data not null
          LeadershipConfigPart.validateJSON(data['leadership']);
        }
        // validate the optional field `log_forwarding`
        if (data['log_forwarding']) { // data not null
          LogForwardingConfigPart.validateJSON(data['log_forwarding']);
        }
        // validate the optional field `message_queue_info`
        if (data['message_queue_info']) { // data not null
          GatewayMessageQueueInfo.validateJSON(data['message_queue_info']);
        }
        // validate the optional field `migrations`
        if (data['migrations']) { // data not null
          MigrationsConfigPart.validateJSON(data['migrations']);
        }
        // validate the optional field `producers`
        if (data['producers']) { // data not null
          ProducersConfigPart.validateJSON(data['producers']);
        }
        // validate the optional field `rotators`
        if (data['rotators']) { // data not null
          RotatorsConfigPart.validateJSON(data['rotators']);
        }
        // validate the optional field `saml`
        if (data['saml']) { // data not null
          DefaultConfigPart.validateJSON(data['saml']);
        }

        return true;
    }


}



/**
 * @member {module:model/AdminsConfigPart} admins
 */
AkeylessGatewayConfig.prototype['admins'] = undefined;

/**
 * @member {module:model/CaCertificatesConfigPart} ca_certificates
 */
AkeylessGatewayConfig.prototype['ca_certificates'] = undefined;

/**
 * @member {module:model/CacheConfigPart} cache
 */
AkeylessGatewayConfig.prototype['cache'] = undefined;

/**
 * @member {module:model/CFConfigPart} cf
 */
AkeylessGatewayConfig.prototype['cf'] = undefined;

/**
 * @member {String} config_protection_key_name
 */
AkeylessGatewayConfig.prototype['config_protection_key_name'] = undefined;

/**
 * @member {module:model/GeneralConfigPart} general
 */
AkeylessGatewayConfig.prototype['general'] = undefined;

/**
 * @member {module:model/K8SAuthsConfigPart} k8s_auths
 */
AkeylessGatewayConfig.prototype['k8s_auths'] = undefined;

/**
 * @member {module:model/KerberosConfigPart} kerberos
 */
AkeylessGatewayConfig.prototype['kerberos'] = undefined;

/**
 * @member {module:model/KMIPConfigPart} kmip_clients
 */
AkeylessGatewayConfig.prototype['kmip_clients'] = undefined;

/**
 * @member {module:model/LdapConfigPart} ldap
 */
AkeylessGatewayConfig.prototype['ldap'] = undefined;

/**
 * @member {module:model/LeadershipConfigPart} leadership
 */
AkeylessGatewayConfig.prototype['leadership'] = undefined;

/**
 * @member {module:model/LogForwardingConfigPart} log_forwarding
 */
AkeylessGatewayConfig.prototype['log_forwarding'] = undefined;

/**
 * @member {module:model/GatewayMessageQueueInfo} message_queue_info
 */
AkeylessGatewayConfig.prototype['message_queue_info'] = undefined;

/**
 * @member {module:model/MigrationsConfigPart} migrations
 */
AkeylessGatewayConfig.prototype['migrations'] = undefined;

/**
 * @member {module:model/ProducersConfigPart} producers
 */
AkeylessGatewayConfig.prototype['producers'] = undefined;

/**
 * @member {module:model/RotatorsConfigPart} rotators
 */
AkeylessGatewayConfig.prototype['rotators'] = undefined;

/**
 * @member {module:model/DefaultConfigPart} saml
 */
AkeylessGatewayConfig.prototype['saml'] = undefined;

/**
 * @member {Number} version
 */
AkeylessGatewayConfig.prototype['version'] = undefined;






export default AkeylessGatewayConfig;

