/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CertificateScanTarget model module.
 * @module model/CertificateScanTarget
 * @version 5.0.19
 */
class CertificateScanTarget {
    /**
     * Constructs a new <code>CertificateScanTarget</code>.
     * @alias module:model/CertificateScanTarget
     */
    constructor() { 
        
        CertificateScanTarget.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CertificateScanTarget</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertificateScanTarget} obj Optional instance to populate.
     * @return {module:model/CertificateScanTarget} The populated <code>CertificateScanTarget</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CertificateScanTarget();

            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('portRanges')) {
                obj['portRanges'] = ApiClient.convertToType(data['portRanges'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CertificateScanTarget</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CertificateScanTarget</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['portRanges'] && !(typeof data['portRanges'] === 'string' || data['portRanges'] instanceof String)) {
            throw new Error("Expected the field `portRanges` to be a primitive type in the JSON string but got " + data['portRanges']);
        }

        return true;
    }


}



/**
 * @member {String} host
 */
CertificateScanTarget.prototype['host'] = undefined;

/**
 * @member {String} portRanges
 */
CertificateScanTarget.prototype['portRanges'] = undefined;






export default CertificateScanTarget;

