/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CfInfo model module.
 * @module model/CfInfo
 * @version 5.0.1
 */
class CfInfo {
    /**
     * Constructs a new <code>CfInfo</code>.
     * @alias module:model/CfInfo
     */
    constructor() { 
        
        CfInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CfInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CfInfo} obj Optional instance to populate.
     * @return {module:model/CfInfo} The populated <code>CfInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CfInfo();

            if (data.hasOwnProperty('cf_name')) {
                obj['cf_name'] = ApiClient.convertToType(data['cf_name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CfInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CfInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['cf_name'] && !(typeof data['cf_name'] === 'string' || data['cf_name'] instanceof String)) {
            throw new Error("Expected the field `cf_name` to be a primitive type in the JSON string but got " + data['cf_name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['hash'] && !(typeof data['hash'] === 'string' || data['hash'] instanceof String)) {
            throw new Error("Expected the field `hash` to be a primitive type in the JSON string but got " + data['hash']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }

        return true;
    }


}



/**
 * @member {String} cf_name
 */
CfInfo.prototype['cf_name'] = undefined;

/**
 * @member {String} description
 */
CfInfo.prototype['description'] = undefined;

/**
 * @member {String} hash
 */
CfInfo.prototype['hash'] = undefined;

/**
 * @member {String} id
 */
CfInfo.prototype['id'] = undefined;






export default CfInfo;

