/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DesktopAppConf model module.
 * @module model/DesktopAppConf
 * @version 5.0.13
 */
class DesktopAppConf {
    /**
     * Constructs a new <code>DesktopAppConf</code>.
     * @alias module:model/DesktopAppConf
     */
    constructor() { 
        
        DesktopAppConf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DesktopAppConf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DesktopAppConf} obj Optional instance to populate.
     * @return {module:model/DesktopAppConf} The populated <code>DesktopAppConf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DesktopAppConf();

            if (data.hasOwnProperty('default_cert_issuer_id')) {
                obj['default_cert_issuer_id'] = ApiClient.convertToType(data['default_cert_issuer_id'], 'Number');
            }
            if (data.hasOwnProperty('default_cert_issuer_name')) {
                obj['default_cert_issuer_name'] = ApiClient.convertToType(data['default_cert_issuer_name'], 'String');
            }
            if (data.hasOwnProperty('secure_web_access_url')) {
                obj['secure_web_access_url'] = ApiClient.convertToType(data['secure_web_access_url'], 'String');
            }
            if (data.hasOwnProperty('secure_web_proxy_url')) {
                obj['secure_web_proxy_url'] = ApiClient.convertToType(data['secure_web_proxy_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DesktopAppConf</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DesktopAppConf</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['default_cert_issuer_name'] && !(typeof data['default_cert_issuer_name'] === 'string' || data['default_cert_issuer_name'] instanceof String)) {
            throw new Error("Expected the field `default_cert_issuer_name` to be a primitive type in the JSON string but got " + data['default_cert_issuer_name']);
        }
        // ensure the json data is a string
        if (data['secure_web_access_url'] && !(typeof data['secure_web_access_url'] === 'string' || data['secure_web_access_url'] instanceof String)) {
            throw new Error("Expected the field `secure_web_access_url` to be a primitive type in the JSON string but got " + data['secure_web_access_url']);
        }
        // ensure the json data is a string
        if (data['secure_web_proxy_url'] && !(typeof data['secure_web_proxy_url'] === 'string' || data['secure_web_proxy_url'] instanceof String)) {
            throw new Error("Expected the field `secure_web_proxy_url` to be a primitive type in the JSON string but got " + data['secure_web_proxy_url']);
        }

        return true;
    }


}



/**
 * @member {Number} default_cert_issuer_id
 */
DesktopAppConf.prototype['default_cert_issuer_id'] = undefined;

/**
 * @member {String} default_cert_issuer_name
 */
DesktopAppConf.prototype['default_cert_issuer_name'] = undefined;

/**
 * @member {String} secure_web_access_url
 */
DesktopAppConf.prototype['secure_web_access_url'] = undefined;

/**
 * @member {String} secure_web_proxy_url
 */
DesktopAppConf.prototype['secure_web_proxy_url'] = undefined;






export default DesktopAppConf;

