/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DynamicSecretTmpCredsDelete model module.
 * @module model/DynamicSecretTmpCredsDelete
 * @version 5.0.8
 */
class DynamicSecretTmpCredsDelete {
    /**
     * Constructs a new <code>DynamicSecretTmpCredsDelete</code>.
     * dynamicSecretTmpCredsDelete is a command that deletes dynamic secret temp creds
     * @alias module:model/DynamicSecretTmpCredsDelete
     * @param name {String} Dynamic secret name
     */
    constructor(name) { 
        
        DynamicSecretTmpCredsDelete.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['json'] = false;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DynamicSecretTmpCredsDelete</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DynamicSecretTmpCredsDelete} obj Optional instance to populate.
     * @return {module:model/DynamicSecretTmpCredsDelete} The populated <code>DynamicSecretTmpCredsDelete</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DynamicSecretTmpCredsDelete();

            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('revoke-all')) {
                obj['revoke-all'] = ApiClient.convertToType(data['revoke-all'], 'Boolean');
            }
            if (data.hasOwnProperty('soft-delete')) {
                obj['soft-delete'] = ApiClient.convertToType(data['soft-delete'], 'Boolean');
            }
            if (data.hasOwnProperty('tmp-creds-id')) {
                obj['tmp-creds-id'] = ApiClient.convertToType(data['tmp-creds-id'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('uid-token')) {
                obj['uid-token'] = ApiClient.convertToType(data['uid-token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DynamicSecretTmpCredsDelete</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DynamicSecretTmpCredsDelete</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DynamicSecretTmpCredsDelete.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['tmp-creds-id'] && !(typeof data['tmp-creds-id'] === 'string' || data['tmp-creds-id'] instanceof String)) {
            throw new Error("Expected the field `tmp-creds-id` to be a primitive type in the JSON string but got " + data['tmp-creds-id']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['uid-token'] && !(typeof data['uid-token'] === 'string' || data['uid-token'] instanceof String)) {
            throw new Error("Expected the field `uid-token` to be a primitive type in the JSON string but got " + data['uid-token']);
        }

        return true;
    }


}

DynamicSecretTmpCredsDelete.RequiredProperties = ["name"];

/**
 * Host
 * @member {String} host
 */
DynamicSecretTmpCredsDelete.prototype['host'] = undefined;

/**
 * Set output format to JSON
 * @member {Boolean} json
 * @default false
 */
DynamicSecretTmpCredsDelete.prototype['json'] = false;

/**
 * Dynamic secret name
 * @member {String} name
 */
DynamicSecretTmpCredsDelete.prototype['name'] = undefined;

/**
 * Revoke All Temp Creds
 * @member {Boolean} revoke-all
 */
DynamicSecretTmpCredsDelete.prototype['revoke-all'] = undefined;

/**
 * Soft Delete
 * @member {Boolean} soft-delete
 */
DynamicSecretTmpCredsDelete.prototype['soft-delete'] = undefined;

/**
 * Tmp Creds ID
 * @member {String} tmp-creds-id
 */
DynamicSecretTmpCredsDelete.prototype['tmp-creds-id'] = undefined;

/**
 * Authentication token (see `/auth` and `/configure`)
 * @member {String} token
 */
DynamicSecretTmpCredsDelete.prototype['token'] = undefined;

/**
 * The universal identity token, Required only for universal_identity authentication
 * @member {String} uid-token
 */
DynamicSecretTmpCredsDelete.prototype['uid-token'] = undefined;






export default DynamicSecretTmpCredsDelete;

