/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GatewayStartProducer model module.
 * @module model/GatewayStartProducer
 * @version 5.0.33
 */
class GatewayStartProducer {
    /**
     * Constructs a new <code>GatewayStartProducer</code>.
     * gatewayStartProducer is a command that starts producer [Deprecated: Use set-item-state command]
     * @alias module:model/GatewayStartProducer
     * @param name {String} Dynamic secret name
     */
    constructor(name) { 
        
        GatewayStartProducer.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['json'] = false;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>GatewayStartProducer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GatewayStartProducer} obj Optional instance to populate.
     * @return {module:model/GatewayStartProducer} The populated <code>GatewayStartProducer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GatewayStartProducer();

            if (data.hasOwnProperty('ara-enabled')) {
                obj['ara-enabled'] = ApiClient.convertToType(data['ara-enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('input-rule')) {
                obj['input-rule'] = ApiClient.convertToType(data['input-rule'], ['String']);
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('output-rule')) {
                obj['output-rule'] = ApiClient.convertToType(data['output-rule'], ['String']);
            }
            if (data.hasOwnProperty('skip_dry_run')) {
                obj['skip_dry_run'] = ApiClient.convertToType(data['skip_dry_run'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('uid-token')) {
                obj['uid-token'] = ApiClient.convertToType(data['uid-token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GatewayStartProducer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GatewayStartProducer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GatewayStartProducer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['input-rule'])) {
            throw new Error("Expected the field `input-rule` to be an array in the JSON data but got " + data['input-rule']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['output-rule'])) {
            throw new Error("Expected the field `output-rule` to be an array in the JSON data but got " + data['output-rule']);
        }
        // ensure the json data is a string
        if (data['skip_dry_run'] && !(typeof data['skip_dry_run'] === 'string' || data['skip_dry_run'] instanceof String)) {
            throw new Error("Expected the field `skip_dry_run` to be a primitive type in the JSON string but got " + data['skip_dry_run']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['uid-token'] && !(typeof data['uid-token'] === 'string' || data['uid-token'] instanceof String)) {
            throw new Error("Expected the field `uid-token` to be a primitive type in the JSON string but got " + data['uid-token']);
        }

        return true;
    }


}

GatewayStartProducer.RequiredProperties = ["name"];

/**
 * Enable or disable Agentic Runtime Authority rule enforcement for this item. Mirrors commands.AgenticRulesParams.AraEnabled.
 * @member {Boolean} ara-enabled
 */
GatewayStartProducer.prototype['ara-enabled'] = undefined;

/**
 * Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input) Mirrors commands.AgenticRulesParams — kept separate because ResourceDS cannot embed it (different package, different struct layout).
 * @member {Array.<String>} input-rule
 */
GatewayStartProducer.prototype['input-rule'] = undefined;

/**
 * Set output format to JSON
 * @member {Boolean} json
 * @default false
 */
GatewayStartProducer.prototype['json'] = false;

/**
 * Dynamic secret name
 * @member {String} name
 */
GatewayStartProducer.prototype['name'] = undefined;

/**
 * Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
 * @member {Array.<String>} output-rule
 */
GatewayStartProducer.prototype['output-rule'] = undefined;

/**
 * If set, dry-run will be skipped
 * @member {String} skip_dry_run
 */
GatewayStartProducer.prototype['skip_dry_run'] = undefined;

/**
 * Authentication token (see `/auth` and `/configure`)
 * @member {String} token
 */
GatewayStartProducer.prototype['token'] = undefined;

/**
 * The universal identity token, Required only for universal_identity authentication
 * @member {String} uid-token
 */
GatewayStartProducer.prototype['uid-token'] = undefined;






export default GatewayStartProducer;

