/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetLastUserEventStatus model module.
 * @module model/GetLastUserEventStatus
 * @version 4.2.0
 */
class GetLastUserEventStatus {
    /**
     * Constructs a new <code>GetLastUserEventStatus</code>.
     * @alias module:model/GetLastUserEventStatus
     * @param eventType {String} 
     * @param itemName {String} Event item name
     * @param itemType {String} Event item type can be either \"target\" or type of item eg \"static_secret\"/\"dynamic_secret\" To get type of some item run `akeyless describe-item -n {ITEM_NAME} --jq-expression .item_type`
     */
    constructor(eventType, itemName, itemType) { 
        
        GetLastUserEventStatus.initialize(this, eventType, itemName, itemType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, eventType, itemName, itemType) { 
        obj['event-type'] = eventType;
        obj['item-name'] = itemName;
        obj['item-type'] = itemType;
    }

    /**
     * Constructs a <code>GetLastUserEventStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetLastUserEventStatus} obj Optional instance to populate.
     * @return {module:model/GetLastUserEventStatus} The populated <code>GetLastUserEventStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetLastUserEventStatus();

            if (data.hasOwnProperty('event-source')) {
                obj['event-source'] = ApiClient.convertToType(data['event-source'], 'String');
            }
            if (data.hasOwnProperty('event-type')) {
                obj['event-type'] = ApiClient.convertToType(data['event-type'], 'String');
            }
            if (data.hasOwnProperty('item-name')) {
                obj['item-name'] = ApiClient.convertToType(data['item-name'], 'String');
            }
            if (data.hasOwnProperty('item-type')) {
                obj['item-type'] = ApiClient.convertToType(data['item-type'], 'String');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], 'Boolean');
            }
            if (data.hasOwnProperty('time-back')) {
                obj['time-back'] = ApiClient.convertToType(data['time-back'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('uid-token')) {
                obj['uid-token'] = ApiClient.convertToType(data['uid-token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} event-source
 */
GetLastUserEventStatus.prototype['event-source'] = undefined;

/**
 * @member {String} event-type
 */
GetLastUserEventStatus.prototype['event-type'] = undefined;

/**
 * Event item name
 * @member {String} item-name
 */
GetLastUserEventStatus.prototype['item-name'] = undefined;

/**
 * Event item type can be either \"target\" or type of item eg \"static_secret\"/\"dynamic_secret\" To get type of some item run `akeyless describe-item -n {ITEM_NAME} --jq-expression .item_type`
 * @member {String} item-type
 */
GetLastUserEventStatus.prototype['item-type'] = undefined;

/**
 * Set output format to JSON
 * @member {Boolean} json
 * @default false
 */
GetLastUserEventStatus.prototype['json'] = false;

/**
 * The time back to search the event, for example if the value is \"5m\" we will return the last user event issued in the last 5 minutes. By default, we will search without any time boundary.
 * @member {String} time-back
 */
GetLastUserEventStatus.prototype['time-back'] = undefined;

/**
 * Authentication token (see `/auth` and `/configure`)
 * @member {String} token
 */
GetLastUserEventStatus.prototype['token'] = undefined;

/**
 * The universal identity token, Required only for universal_identity authentication
 * @member {String} uid-token
 */
GetLastUserEventStatus.prototype['uid-token'] = undefined;






export default GetLastUserEventStatus;

