/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HTTPChallengeInfo model module.
 * @module model/HTTPChallengeInfo
 * @version 5.0.24
 */
class HTTPChallengeInfo {
    /**
     * Constructs a new <code>HTTPChallengeInfo</code>.
     * HTTPChallengeInfo contains HTTP-01 challenge details for user display
     * @alias module:model/HTTPChallengeInfo
     */
    constructor() { 
        
        HTTPChallengeInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HTTPChallengeInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HTTPChallengeInfo} obj Optional instance to populate.
     * @return {module:model/HTTPChallengeInfo} The populated <code>HTTPChallengeInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HTTPChallengeInfo();

            if (data.hasOwnProperty('file_content')) {
                obj['file_content'] = ApiClient.convertToType(data['file_content'], 'String');
            }
            if (data.hasOwnProperty('file_path')) {
                obj['file_path'] = ApiClient.convertToType(data['file_path'], 'String');
            }
            if (data.hasOwnProperty('instructions')) {
                obj['instructions'] = ApiClient.convertToType(data['instructions'], 'String');
            }
            if (data.hasOwnProperty('key_auth')) {
                obj['key_auth'] = ApiClient.convertToType(data['key_auth'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HTTPChallengeInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HTTPChallengeInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['file_content'] && !(typeof data['file_content'] === 'string' || data['file_content'] instanceof String)) {
            throw new Error("Expected the field `file_content` to be a primitive type in the JSON string but got " + data['file_content']);
        }
        // ensure the json data is a string
        if (data['file_path'] && !(typeof data['file_path'] === 'string' || data['file_path'] instanceof String)) {
            throw new Error("Expected the field `file_path` to be a primitive type in the JSON string but got " + data['file_path']);
        }
        // ensure the json data is a string
        if (data['instructions'] && !(typeof data['instructions'] === 'string' || data['instructions'] instanceof String)) {
            throw new Error("Expected the field `instructions` to be a primitive type in the JSON string but got " + data['instructions']);
        }
        // ensure the json data is a string
        if (data['key_auth'] && !(typeof data['key_auth'] === 'string' || data['key_auth'] instanceof String)) {
            throw new Error("Expected the field `key_auth` to be a primitive type in the JSON string but got " + data['key_auth']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }

        return true;
    }


}



/**
 * @member {String} file_content
 */
HTTPChallengeInfo.prototype['file_content'] = undefined;

/**
 * @member {String} file_path
 */
HTTPChallengeInfo.prototype['file_path'] = undefined;

/**
 * @member {String} instructions
 */
HTTPChallengeInfo.prototype['instructions'] = undefined;

/**
 * @member {String} key_auth
 */
HTTPChallengeInfo.prototype['key_auth'] = undefined;

/**
 * @member {String} token
 */
HTTPChallengeInfo.prototype['token'] = undefined;






export default HTTPChallengeInfo;

