/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetappStorage model module.
 * @module model/NetappStorage
 * @version 5.0.23
 */
class NetappStorage {
    /**
     * Constructs a new <code>NetappStorage</code>.
     * @alias module:model/NetappStorage
     */
    constructor() { 
        
        NetappStorage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NetappStorage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetappStorage} obj Optional instance to populate.
     * @return {module:model/NetappStorage} The populated <code>NetappStorage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetappStorage();

            if (data.hasOwnProperty('access_key_id')) {
                obj['access_key_id'] = ApiClient.convertToType(data['access_key_id'], 'String');
            }
            if (data.hasOwnProperty('access_key_secret')) {
                obj['access_key_secret'] = ApiClient.convertToType(data['access_key_secret'], 'String');
            }
            if (data.hasOwnProperty('auth_type')) {
                obj['auth_type'] = ApiClient.convertToType(data['auth_type'], 'String');
            }
            if (data.hasOwnProperty('bucket')) {
                obj['bucket'] = ApiClient.convertToType(data['bucket'], 'String');
            }
            if (data.hasOwnProperty('endpoint_url')) {
                obj['endpoint_url'] = ApiClient.convertToType(data['endpoint_url'], 'String');
            }
            if (data.hasOwnProperty('prefix')) {
                obj['prefix'] = ApiClient.convertToType(data['prefix'], 'String');
            }
            if (data.hasOwnProperty('region')) {
                obj['region'] = ApiClient.convertToType(data['region'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NetappStorage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NetappStorage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['access_key_id'] && !(typeof data['access_key_id'] === 'string' || data['access_key_id'] instanceof String)) {
            throw new Error("Expected the field `access_key_id` to be a primitive type in the JSON string but got " + data['access_key_id']);
        }
        // ensure the json data is a string
        if (data['access_key_secret'] && !(typeof data['access_key_secret'] === 'string' || data['access_key_secret'] instanceof String)) {
            throw new Error("Expected the field `access_key_secret` to be a primitive type in the JSON string but got " + data['access_key_secret']);
        }
        // ensure the json data is a string
        if (data['auth_type'] && !(typeof data['auth_type'] === 'string' || data['auth_type'] instanceof String)) {
            throw new Error("Expected the field `auth_type` to be a primitive type in the JSON string but got " + data['auth_type']);
        }
        // ensure the json data is a string
        if (data['bucket'] && !(typeof data['bucket'] === 'string' || data['bucket'] instanceof String)) {
            throw new Error("Expected the field `bucket` to be a primitive type in the JSON string but got " + data['bucket']);
        }
        // ensure the json data is a string
        if (data['endpoint_url'] && !(typeof data['endpoint_url'] === 'string' || data['endpoint_url'] instanceof String)) {
            throw new Error("Expected the field `endpoint_url` to be a primitive type in the JSON string but got " + data['endpoint_url']);
        }
        // ensure the json data is a string
        if (data['prefix'] && !(typeof data['prefix'] === 'string' || data['prefix'] instanceof String)) {
            throw new Error("Expected the field `prefix` to be a primitive type in the JSON string but got " + data['prefix']);
        }
        // ensure the json data is a string
        if (data['region'] && !(typeof data['region'] === 'string' || data['region'] instanceof String)) {
            throw new Error("Expected the field `region` to be a primitive type in the JSON string but got " + data['region']);
        }

        return true;
    }


}



/**
 * @member {String} access_key_id
 */
NetappStorage.prototype['access_key_id'] = undefined;

/**
 * @member {String} access_key_secret
 */
NetappStorage.prototype['access_key_secret'] = undefined;

/**
 * @member {String} auth_type
 */
NetappStorage.prototype['auth_type'] = undefined;

/**
 * @member {String} bucket
 */
NetappStorage.prototype['bucket'] = undefined;

/**
 * @member {String} endpoint_url
 */
NetappStorage.prototype['endpoint_url'] = undefined;

/**
 * @member {String} prefix
 */
NetappStorage.prototype['prefix'] = undefined;

/**
 * @member {String} region
 */
NetappStorage.prototype['region'] = undefined;






export default NetappStorage;

