/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NullTime model module.
 * @module model/NullTime
 * @version 5.0.13
 */
class NullTime {
    /**
     * Constructs a new <code>NullTime</code>.
     * NullTime implements the [Scanner] interface so it can be used as a scan destination, similar to [NullString].
     * @alias module:model/NullTime
     */
    constructor() { 
        
        NullTime.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NullTime</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NullTime} obj Optional instance to populate.
     * @return {module:model/NullTime} The populated <code>NullTime</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NullTime();

            if (data.hasOwnProperty('Time')) {
                obj['Time'] = ApiClient.convertToType(data['Time'], 'Date');
            }
            if (data.hasOwnProperty('Valid')) {
                obj['Valid'] = ApiClient.convertToType(data['Valid'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>NullTime</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>NullTime</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Date} Time
 */
NullTime.prototype['Time'] = undefined;

/**
 * @member {Boolean} Valid
 */
NullTime.prototype['Valid'] = undefined;






export default NullTime;

