/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonalFolderGlobalMappingSettings model module.
 * @module model/PersonalFolderGlobalMappingSettings
 * @version 5.0.33
 */
class PersonalFolderGlobalMappingSettings {
    /**
     * Constructs a new <code>PersonalFolderGlobalMappingSettings</code>.
     * @alias module:model/PersonalFolderGlobalMappingSettings
     */
    constructor() { 
        
        PersonalFolderGlobalMappingSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonalFolderGlobalMappingSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonalFolderGlobalMappingSettings} obj Optional instance to populate.
     * @return {module:model/PersonalFolderGlobalMappingSettings} The populated <code>PersonalFolderGlobalMappingSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonalFolderGlobalMappingSettings();

            if (data.hasOwnProperty('enable')) {
                obj['enable'] = ApiClient.convertToType(data['enable'], 'Boolean');
            }
            if (data.hasOwnProperty('unique_identifier_claim')) {
                obj['unique_identifier_claim'] = ApiClient.convertToType(data['unique_identifier_claim'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PersonalFolderGlobalMappingSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PersonalFolderGlobalMappingSettings</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['unique_identifier_claim'] && !(typeof data['unique_identifier_claim'] === 'string' || data['unique_identifier_claim'] instanceof String)) {
            throw new Error("Expected the field `unique_identifier_claim` to be a primitive type in the JSON string but got " + data['unique_identifier_claim']);
        }

        return true;
    }


}



/**
 * @member {Boolean} enable
 */
PersonalFolderGlobalMappingSettings.prototype['enable'] = undefined;

/**
 * @member {String} unique_identifier_claim
 */
PersonalFolderGlobalMappingSettings.prototype['unique_identifier_claim'] = undefined;






export default PersonalFolderGlobalMappingSettings;

