/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PoliciesList model module.
 * @module model/PoliciesList
 * @version 5.0.22
 */
class PoliciesList {
    /**
     * Constructs a new <code>PoliciesList</code>.
     * @alias module:model/PoliciesList
     */
    constructor() { 
        
        PoliciesList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['json'] = false;
    }

    /**
     * Constructs a <code>PoliciesList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PoliciesList} obj Optional instance to populate.
     * @return {module:model/PoliciesList} The populated <code>PoliciesList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PoliciesList();

            if (data.hasOwnProperty('aggregate')) {
                obj['aggregate'] = ApiClient.convertToType(data['aggregate'], 'Boolean');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], 'Boolean');
            }
            if (data.hasOwnProperty('object-type')) {
                obj['object-type'] = ApiClient.convertToType(data['object-type'], ['String']);
            }
            if (data.hasOwnProperty('paths')) {
                obj['paths'] = ApiClient.convertToType(data['paths'], ['String']);
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('types')) {
                obj['types'] = ApiClient.convertToType(data['types'], ['String']);
            }
            if (data.hasOwnProperty('uid-token')) {
                obj['uid-token'] = ApiClient.convertToType(data['uid-token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PoliciesList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PoliciesList</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['object-type'])) {
            throw new Error("Expected the field `object-type` to be an array in the JSON data but got " + data['object-type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['paths'])) {
            throw new Error("Expected the field `paths` to be an array in the JSON data but got " + data['paths']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['types'])) {
            throw new Error("Expected the field `types` to be an array in the JSON data but got " + data['types']);
        }
        // ensure the json data is a string
        if (data['uid-token'] && !(typeof data['uid-token'] === 'string' || data['uid-token'] instanceof String)) {
            throw new Error("Expected the field `uid-token` to be a primitive type in the JSON string but got " + data['uid-token']);
        }

        return true;
    }


}



/**
 * Aggregate missing configurations from parent policies (requires --paths)
 * @member {Boolean} aggregate
 */
PoliciesList.prototype['aggregate'] = undefined;

/**
 * Set output format to JSON
 * @member {Boolean} json
 * @default false
 */
PoliciesList.prototype['json'] = false;

/**
 * Optional object types filter (items or targets)
 * @member {Array.<String>} object-type
 */
PoliciesList.prototype['object-type'] = undefined;

/**
 * Filter by exact policy paths
 * @member {Array.<String>} paths
 */
PoliciesList.prototype['paths'] = undefined;

/**
 * Authentication token (see `/auth` and `/configure`)
 * @member {String} token
 */
PoliciesList.prototype['token'] = undefined;

/**
 * Filter by policy types
 * @member {Array.<String>} types
 */
PoliciesList.prototype['types'] = undefined;

/**
 * The universal identity token, Required only for universal_identity authentication
 * @member {String} uid-token
 */
PoliciesList.prototype['uid-token'] = undefined;






export default PoliciesList;

