/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseStopShareItem from './ResponseStopShareItem';
import SharingItemFullInfo from './SharingItemFullInfo';

/**
 * The ShareItemOutput model module.
 * @module model/ShareItemOutput
 * @version 5.0.6
 */
class ShareItemOutput {
    /**
     * Constructs a new <code>ShareItemOutput</code>.
     * @alias module:model/ShareItemOutput
     */
    constructor() { 
        
        ShareItemOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShareItemOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShareItemOutput} obj Optional instance to populate.
     * @return {module:model/ShareItemOutput} The populated <code>ShareItemOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShareItemOutput();

            if (data.hasOwnProperty('email_error')) {
                obj['email_error'] = ApiClient.convertToType(data['email_error'], {'String': 'String'});
            }
            if (data.hasOwnProperty('items_error')) {
                obj['items_error'] = ApiClient.convertToType(data['items_error'], [ResponseStopShareItem]);
            }
            if (data.hasOwnProperty('s_token')) {
                obj['s_token'] = ApiClient.convertToType(data['s_token'], 'String');
            }
            if (data.hasOwnProperty('shared_users')) {
                obj['shared_users'] = ApiClient.convertToType(data['shared_users'], ['String']);
            }
            if (data.hasOwnProperty('shared_users_full_info')) {
                obj['shared_users_full_info'] = ApiClient.convertToType(data['shared_users_full_info'], [SharingItemFullInfo]);
            }
            if (data.hasOwnProperty('sharing_url')) {
                obj['sharing_url'] = ApiClient.convertToType(data['sharing_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShareItemOutput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShareItemOutput</code>.
     */
    static validateJSON(data) {
        if (data['items_error']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['items_error'])) {
                throw new Error("Expected the field `items_error` to be an array in the JSON data but got " + data['items_error']);
            }
            // validate the optional field `items_error` (array)
            for (const item of data['items_error']) {
                ResponseStopShareItem.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['s_token'] && !(typeof data['s_token'] === 'string' || data['s_token'] instanceof String)) {
            throw new Error("Expected the field `s_token` to be a primitive type in the JSON string but got " + data['s_token']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['shared_users'])) {
            throw new Error("Expected the field `shared_users` to be an array in the JSON data but got " + data['shared_users']);
        }
        if (data['shared_users_full_info']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['shared_users_full_info'])) {
                throw new Error("Expected the field `shared_users_full_info` to be an array in the JSON data but got " + data['shared_users_full_info']);
            }
            // validate the optional field `shared_users_full_info` (array)
            for (const item of data['shared_users_full_info']) {
                SharingItemFullInfo.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['sharing_url'] && !(typeof data['sharing_url'] === 'string' || data['sharing_url'] instanceof String)) {
            throw new Error("Expected the field `sharing_url` to be a primitive type in the JSON string but got " + data['sharing_url']);
        }

        return true;
    }


}



/**
 * @member {Object.<String, String>} email_error
 */
ShareItemOutput.prototype['email_error'] = undefined;

/**
 * @member {Array.<module:model/ResponseStopShareItem>} items_error
 */
ShareItemOutput.prototype['items_error'] = undefined;

/**
 * @member {String} s_token
 */
ShareItemOutput.prototype['s_token'] = undefined;

/**
 * @member {Array.<String>} shared_users
 */
ShareItemOutput.prototype['shared_users'] = undefined;

/**
 * @member {Array.<module:model/SharingItemFullInfo>} shared_users_full_info
 */
ShareItemOutput.prototype['shared_users_full_info'] = undefined;

/**
 * @member {String} sharing_url
 */
ShareItemOutput.prototype['sharing_url'] = undefined;






export default ShareItemOutput;

