/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SlackNotiForwarderDetails model module.
 * @module model/SlackNotiForwarderDetails
 * @version 5.0.19
 */
class SlackNotiForwarderDetails {
    /**
     * Constructs a new <code>SlackNotiForwarderDetails</code>.
     * @alias module:model/SlackNotiForwarderDetails
     */
    constructor() { 
        
        SlackNotiForwarderDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SlackNotiForwarderDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SlackNotiForwarderDetails} obj Optional instance to populate.
     * @return {module:model/SlackNotiForwarderDetails} The populated <code>SlackNotiForwarderDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SlackNotiForwarderDetails();

            if (data.hasOwnProperty('endpoint_url')) {
                obj['endpoint_url'] = ApiClient.convertToType(data['endpoint_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SlackNotiForwarderDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SlackNotiForwarderDetails</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['endpoint_url'] && !(typeof data['endpoint_url'] === 'string' || data['endpoint_url'] instanceof String)) {
            throw new Error("Expected the field `endpoint_url` to be a primitive type in the JSON string but got " + data['endpoint_url']);
        }

        return true;
    }


}



/**
 * @member {String} endpoint_url
 */
SlackNotiForwarderDetails.prototype['endpoint_url'] = undefined;






export default SlackNotiForwarderDetails;

