/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TargetCreateGoogleTrust model module.
 * @module model/TargetCreateGoogleTrust
 * @version 5.0.24
 */
class TargetCreateGoogleTrust {
    /**
     * Constructs a new <code>TargetCreateGoogleTrust</code>.
     * targetCreateGoogleTrust is a command that creates a new Google Trust target
     * @alias module:model/TargetCreateGoogleTrust
     * @param email {String} Email address for ACME account registration
     * @param name {String} Target name
     */
    constructor(email, name) { 
        
        TargetCreateGoogleTrust.initialize(this, email, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, name) { 
        obj['acme-challenge'] = 'dns';
        obj['email'] = email;
        obj['google-trust-url'] = 'production';
        obj['json'] = false;
        obj['name'] = name;
        obj['timeout'] = '5m';
    }

    /**
     * Constructs a <code>TargetCreateGoogleTrust</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TargetCreateGoogleTrust} obj Optional instance to populate.
     * @return {module:model/TargetCreateGoogleTrust} The populated <code>TargetCreateGoogleTrust</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TargetCreateGoogleTrust();

            if (data.hasOwnProperty('acme-challenge')) {
                obj['acme-challenge'] = ApiClient.convertToType(data['acme-challenge'], 'String');
            }
            if (data.hasOwnProperty('delete_protection')) {
                obj['delete_protection'] = ApiClient.convertToType(data['delete_protection'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('dns-target-creds')) {
                obj['dns-target-creds'] = ApiClient.convertToType(data['dns-target-creds'], 'String');
            }
            if (data.hasOwnProperty('eab-hmac-key')) {
                obj['eab-hmac-key'] = ApiClient.convertToType(data['eab-hmac-key'], 'String');
            }
            if (data.hasOwnProperty('eab-key-id')) {
                obj['eab-key-id'] = ApiClient.convertToType(data['eab-key-id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('gcp-project')) {
                obj['gcp-project'] = ApiClient.convertToType(data['gcp-project'], 'String');
            }
            if (data.hasOwnProperty('google-trust-url')) {
                obj['google-trust-url'] = ApiClient.convertToType(data['google-trust-url'], 'String');
            }
            if (data.hasOwnProperty('hosted-zone')) {
                obj['hosted-zone'] = ApiClient.convertToType(data['hosted-zone'], 'String');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], 'Boolean');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('max-versions')) {
                obj['max-versions'] = ApiClient.convertToType(data['max-versions'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('resource-group')) {
                obj['resource-group'] = ApiClient.convertToType(data['resource-group'], 'String');
            }
            if (data.hasOwnProperty('timeout')) {
                obj['timeout'] = ApiClient.convertToType(data['timeout'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('uid-token')) {
                obj['uid-token'] = ApiClient.convertToType(data['uid-token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TargetCreateGoogleTrust</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TargetCreateGoogleTrust</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TargetCreateGoogleTrust.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['acme-challenge'] && !(typeof data['acme-challenge'] === 'string' || data['acme-challenge'] instanceof String)) {
            throw new Error("Expected the field `acme-challenge` to be a primitive type in the JSON string but got " + data['acme-challenge']);
        }
        // ensure the json data is a string
        if (data['delete_protection'] && !(typeof data['delete_protection'] === 'string' || data['delete_protection'] instanceof String)) {
            throw new Error("Expected the field `delete_protection` to be a primitive type in the JSON string but got " + data['delete_protection']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['dns-target-creds'] && !(typeof data['dns-target-creds'] === 'string' || data['dns-target-creds'] instanceof String)) {
            throw new Error("Expected the field `dns-target-creds` to be a primitive type in the JSON string but got " + data['dns-target-creds']);
        }
        // ensure the json data is a string
        if (data['eab-hmac-key'] && !(typeof data['eab-hmac-key'] === 'string' || data['eab-hmac-key'] instanceof String)) {
            throw new Error("Expected the field `eab-hmac-key` to be a primitive type in the JSON string but got " + data['eab-hmac-key']);
        }
        // ensure the json data is a string
        if (data['eab-key-id'] && !(typeof data['eab-key-id'] === 'string' || data['eab-key-id'] instanceof String)) {
            throw new Error("Expected the field `eab-key-id` to be a primitive type in the JSON string but got " + data['eab-key-id']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['gcp-project'] && !(typeof data['gcp-project'] === 'string' || data['gcp-project'] instanceof String)) {
            throw new Error("Expected the field `gcp-project` to be a primitive type in the JSON string but got " + data['gcp-project']);
        }
        // ensure the json data is a string
        if (data['google-trust-url'] && !(typeof data['google-trust-url'] === 'string' || data['google-trust-url'] instanceof String)) {
            throw new Error("Expected the field `google-trust-url` to be a primitive type in the JSON string but got " + data['google-trust-url']);
        }
        // ensure the json data is a string
        if (data['hosted-zone'] && !(typeof data['hosted-zone'] === 'string' || data['hosted-zone'] instanceof String)) {
            throw new Error("Expected the field `hosted-zone` to be a primitive type in the JSON string but got " + data['hosted-zone']);
        }
        // ensure the json data is a string
        if (data['key'] && !(typeof data['key'] === 'string' || data['key'] instanceof String)) {
            throw new Error("Expected the field `key` to be a primitive type in the JSON string but got " + data['key']);
        }
        // ensure the json data is a string
        if (data['max-versions'] && !(typeof data['max-versions'] === 'string' || data['max-versions'] instanceof String)) {
            throw new Error("Expected the field `max-versions` to be a primitive type in the JSON string but got " + data['max-versions']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['resource-group'] && !(typeof data['resource-group'] === 'string' || data['resource-group'] instanceof String)) {
            throw new Error("Expected the field `resource-group` to be a primitive type in the JSON string but got " + data['resource-group']);
        }
        // ensure the json data is a string
        if (data['timeout'] && !(typeof data['timeout'] === 'string' || data['timeout'] instanceof String)) {
            throw new Error("Expected the field `timeout` to be a primitive type in the JSON string but got " + data['timeout']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['uid-token'] && !(typeof data['uid-token'] === 'string' || data['uid-token'] instanceof String)) {
            throw new Error("Expected the field `uid-token` to be a primitive type in the JSON string but got " + data['uid-token']);
        }

        return true;
    }


}

TargetCreateGoogleTrust.RequiredProperties = ["email", "name"];

/**
 * ACME challenge type. Options: [dns]
 * @member {String} acme-challenge
 * @default 'dns'
 */
TargetCreateGoogleTrust.prototype['acme-challenge'] = 'dns';

/**
 * Protection from accidental deletion of this object [true/false]
 * @member {String} delete_protection
 */
TargetCreateGoogleTrust.prototype['delete_protection'] = undefined;

/**
 * Description of the object
 * @member {String} description
 */
TargetCreateGoogleTrust.prototype['description'] = undefined;

/**
 * Name of existing cloud target for DNS credentials. Required when challenge type is dns. Supported providers: AWS, Azure, GCP
 * @member {String} dns-target-creds
 */
TargetCreateGoogleTrust.prototype['dns-target-creds'] = undefined;

/**
 * External Account Binding HMAC key (required for ACME account bootstrap on create)
 * @member {String} eab-hmac-key
 */
TargetCreateGoogleTrust.prototype['eab-hmac-key'] = undefined;

/**
 * External Account Binding key identifier (required for ACME account bootstrap on create)
 * @member {String} eab-key-id
 */
TargetCreateGoogleTrust.prototype['eab-key-id'] = undefined;

/**
 * Email address for ACME account registration
 * @member {String} email
 */
TargetCreateGoogleTrust.prototype['email'] = undefined;

/**
 * GCP Cloud DNS project ID. Optional and can be derived from service account
 * @member {String} gcp-project
 */
TargetCreateGoogleTrust.prototype['gcp-project'] = undefined;

/**
 * Google Trust directory environment. Options: [production/staging]
 * @member {String} google-trust-url
 * @default 'production'
 */
TargetCreateGoogleTrust.prototype['google-trust-url'] = 'production';

/**
 * AWS Route53 hosted zone ID. Required when DNS credentials target is AWS
 * @member {String} hosted-zone
 */
TargetCreateGoogleTrust.prototype['hosted-zone'] = undefined;

/**
 * Set output format to JSON
 * @member {Boolean} json
 * @default false
 */
TargetCreateGoogleTrust.prototype['json'] = false;

/**
 * The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
 * @member {String} key
 */
TargetCreateGoogleTrust.prototype['key'] = undefined;

/**
 * Set the maximum number of versions, limited by the account settings defaults.
 * @member {String} max-versions
 */
TargetCreateGoogleTrust.prototype['max-versions'] = undefined;

/**
 * Target name
 * @member {String} name
 */
TargetCreateGoogleTrust.prototype['name'] = undefined;

/**
 * Azure resource group name. Required when DNS credentials target is Azure
 * @member {String} resource-group
 */
TargetCreateGoogleTrust.prototype['resource-group'] = undefined;

/**
 * Timeout for challenge validation
 * @member {String} timeout
 * @default '5m'
 */
TargetCreateGoogleTrust.prototype['timeout'] = '5m';

/**
 * Authentication token (see `/auth` and `/configure`)
 * @member {String} token
 */
TargetCreateGoogleTrust.prototype['token'] = undefined;

/**
 * The universal identity token, Required only for universal_identity authentication
 * @member {String} uid-token
 */
TargetCreateGoogleTrust.prototype['uid-token'] = undefined;






export default TargetCreateGoogleTrust;

