/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ValidateCertificateChallengeOutput from './ValidateCertificateChallengeOutput';

/**
 * The ValidateCertificateChallenge model module.
 * @module model/ValidateCertificateChallenge
 * @version 5.0.23
 */
class ValidateCertificateChallenge {
    /**
     * Constructs a new <code>ValidateCertificateChallenge</code>.
     * ValidateCertificateChallenge validates HTTP-01 challenge and finalizes certificate issuance (Phase 2)
     * @alias module:model/ValidateCertificateChallenge
     */
    constructor() { 
        
        ValidateCertificateChallenge.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['json'] = false;
        obj['timeout'] = 120;
    }

    /**
     * Constructs a <code>ValidateCertificateChallenge</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValidateCertificateChallenge} obj Optional instance to populate.
     * @return {module:model/ValidateCertificateChallenge} The populated <code>ValidateCertificateChallenge</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValidateCertificateChallenge();

            if (data.hasOwnProperty('Result')) {
                obj['Result'] = ValidateCertificateChallengeOutput.constructFromObject(data['Result']);
            }
            if (data.hasOwnProperty('cert-display-id')) {
                obj['cert-display-id'] = ApiClient.convertToType(data['cert-display-id'], 'String');
            }
            if (data.hasOwnProperty('json')) {
                obj['json'] = ApiClient.convertToType(data['json'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('timeout')) {
                obj['timeout'] = ApiClient.convertToType(data['timeout'], 'Number');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('uid-token')) {
                obj['uid-token'] = ApiClient.convertToType(data['uid-token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ValidateCertificateChallenge</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ValidateCertificateChallenge</code>.
     */
    static validateJSON(data) {
        // validate the optional field `Result`
        if (data['Result']) { // data not null
          ValidateCertificateChallengeOutput.validateJSON(data['Result']);
        }
        // ensure the json data is a string
        if (data['cert-display-id'] && !(typeof data['cert-display-id'] === 'string' || data['cert-display-id'] instanceof String)) {
            throw new Error("Expected the field `cert-display-id` to be a primitive type in the JSON string but got " + data['cert-display-id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['uid-token'] && !(typeof data['uid-token'] === 'string' || data['uid-token'] instanceof String)) {
            throw new Error("Expected the field `uid-token` to be a primitive type in the JSON string but got " + data['uid-token']);
        }

        return true;
    }


}



/**
 * @member {module:model/ValidateCertificateChallengeOutput} Result
 */
ValidateCertificateChallenge.prototype['Result'] = undefined;

/**
 * Certificate display ID from Phase 1
 * @member {String} cert-display-id
 */
ValidateCertificateChallenge.prototype['cert-display-id'] = undefined;

/**
 * Set output format to JSON
 * @member {Boolean} json
 * @default false
 */
ValidateCertificateChallenge.prototype['json'] = false;

/**
 * Certificate name (alternative to cert-display-id)
 * @member {String} name
 */
ValidateCertificateChallenge.prototype['name'] = undefined;

/**
 * Validation timeout in seconds
 * @member {Number} timeout
 * @default 120
 */
ValidateCertificateChallenge.prototype['timeout'] = 120;

/**
 * Authentication token (see `/auth` and `/configure`)
 * @member {String} token
 */
ValidateCertificateChallenge.prototype['token'] = undefined;

/**
 * The universal identity token, Required only for universal_identity authentication
 * @member {String} uid-token
 */
ValidateCertificateChallenge.prototype['uid-token'] = undefined;






export default ValidateCertificateChallenge;

