/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.akeyless);
  }
}(this, function(expect, akeyless) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new akeyless.CertificatePayload();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CertificatePayload', function() {
    it('should create an instance of CertificatePayload', function() {
      // uncomment below and update the code to test CertificatePayload
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be.a(akeyless.CertificatePayload);
    });

    it('should have the property expirationEvents (base name: "expiration_events")', function() {
      // uncomment below and update the code to test the property expirationEvents
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

    it('should have the property folder (base name: "folder")', function() {
      // uncomment below and update the code to test the property folder
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

    it('should have the property maxDialTimeout (base name: "max_dial_timeout")', function() {
      // uncomment below and update the code to test the property maxDialTimeout
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

    it('should have the property maxScanDuration (base name: "max_scan_duration")', function() {
      // uncomment below and update the code to test the property maxScanDuration
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

    it('should have the property maxWorkers (base name: "max_workers")', function() {
      // uncomment below and update the code to test the property maxWorkers
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

    it('should have the property portRanges (base name: "port_ranges")', function() {
      // uncomment below and update the code to test the property portRanges
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

    it('should have the property targets (base name: "targets")', function() {
      // uncomment below and update the code to test the property targets
      //var instance = new akeyless.CertificatePayload();
      //expect(instance).to.be();
    });

  });

}));
