/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.akeyless);
  }
}(this, function(expect, akeyless) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new akeyless.CreateRdpTarget();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateRdpTarget', function() {
    it('should create an instance of CreateRdpTarget', function() {
      // uncomment below and update the code to test CreateRdpTarget
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be.a(akeyless.CreateRdpTarget);
    });

    it('should have the property adminName (base name: "admin_name")', function() {
      // uncomment below and update the code to test the property adminName
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property adminPwd (base name: "admin_pwd")', function() {
      // uncomment below and update the code to test the property adminPwd
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property hostName (base name: "host_name")', function() {
      // uncomment below and update the code to test the property hostName
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property hostPort (base name: "host_port")', function() {
      // uncomment below and update the code to test the property hostPort
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property protectionKey (base name: "protection_key")', function() {
      // uncomment below and update the code to test the property protectionKey
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

    it('should have the property uidToken (base name: "uid-token")', function() {
      // uncomment below and update the code to test the property uidToken
      //var instane = new akeyless.CreateRdpTarget();
      //expect(instance).to.be();
    });

  });

}));
