/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.akeyless);
  }
}(this, function(expect, akeyless) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new akeyless.FileInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FileInfo', function() {
    it('should create an instance of FileInfo', function() {
      // uncomment below and update the code to test FileInfo
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be.a(akeyless.FileInfo);
    });

    it('should have the property blobStorageKey (base name: "blob_storage_key")', function() {
      // uncomment below and update the code to test the property blobStorageKey
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property clientFileSha256 (base name: "client_file_sha256")', function() {
      // uncomment below and update the code to test the property clientFileSha256
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property contentType (base name: "content_type")', function() {
      // uncomment below and update the code to test the property contentType
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property derivationData (base name: "derivation_data")', function() {
      // uncomment below and update the code to test the property derivationData
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property encryptedBlobSha256 (base name: "encrypted_blob_sha256")', function() {
      // uncomment below and update the code to test the property encryptedBlobSha256
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property encryptedSizeBytes (base name: "encrypted_size_bytes")', function() {
      // uncomment below and update the code to test the property encryptedSizeBytes
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property etagAtComplete (base name: "etag_at_complete")', function() {
      // uncomment below and update the code to test the property etagAtComplete
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property extension (base name: "extension")', function() {
      // uncomment below and update the code to test the property extension
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property fileId (base name: "file_id")', function() {
      // uncomment below and update the code to test the property fileId
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property filename (base name: "filename")', function() {
      // uncomment below and update the code to test the property filename
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property plainSizeBytes (base name: "plain_size_bytes")', function() {
      // uncomment below and update the code to test the property plainSizeBytes
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property previousActiveFileInfo (base name: "previous_active_file_info")', function() {
      // uncomment below and update the code to test the property previousActiveFileInfo
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property previousBlobStorageKey (base name: "previous_blob_storage_key")', function() {
      // uncomment below and update the code to test the property previousBlobStorageKey
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property protectionKeyName (base name: "protection_key_name")', function() {
      // uncomment below and update the code to test the property protectionKeyName
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property protectionKeyVersion (base name: "protection_key_version")', function() {
      // uncomment below and update the code to test the property protectionKeyVersion
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

    it('should have the property transactionOwner (base name: "transaction_owner")', function() {
      // uncomment below and update the code to test the property transactionOwner
      //var instance = new akeyless.FileInfo();
      //expect(instance).to.be();
    });

  });

}));
