/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.akeyless);
  }
}(this, function(expect, akeyless) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new akeyless.GatewayCreateProducerNativeK8S();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GatewayCreateProducerNativeK8S', function() {
    it('should create an instance of GatewayCreateProducerNativeK8S', function() {
      // uncomment below and update the code to test GatewayCreateProducerNativeK8S
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be.a(akeyless.GatewayCreateProducerNativeK8S);
    });

    it('should have the property k8sClusterCaCert (base name: "k8s-cluster-ca-cert")', function() {
      // uncomment below and update the code to test the property k8sClusterCaCert
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property k8sClusterEndpoint (base name: "k8s-cluster-endpoint")', function() {
      // uncomment below and update the code to test the property k8sClusterEndpoint
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property k8sClusterToken (base name: "k8s-cluster-token")', function() {
      // uncomment below and update the code to test the property k8sClusterToken
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property k8sNamespace (base name: "k8s-namespace")', function() {
      // uncomment below and update the code to test the property k8sNamespace
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property k8sServiceAccount (base name: "k8s-service-account")', function() {
      // uncomment below and update the code to test the property k8sServiceAccount
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property producerEncryptionKeyName (base name: "producer-encryption-key-name")', function() {
      // uncomment below and update the code to test the property producerEncryptionKeyName
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property token (base name: "token")', function() {
      // uncomment below and update the code to test the property token
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property uidToken (base name: "uid-token")', function() {
      // uncomment below and update the code to test the property uidToken
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property userTtl (base name: "user-ttl")', function() {
      // uncomment below and update the code to test the property userTtl
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instane = new akeyless.GatewayCreateProducerNativeK8S();
      //expect(instance).to.be();
    });

  });

}));
