/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.akeyless);
  }
}(this, function(expect, akeyless) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new akeyless.GoogleTrustTargetDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GoogleTrustTargetDetails', function() {
    it('should create an instance of GoogleTrustTargetDetails', function() {
      // uncomment below and update the code to test GoogleTrustTargetDetails
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be.a(akeyless.GoogleTrustTargetDetails);
    });

    it('should have the property accountKeyPem (base name: "account_key_pem")', function() {
      // uncomment below and update the code to test the property accountKeyPem
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property accountUrl (base name: "account_url")', function() {
      // uncomment below and update the code to test the property accountUrl
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property acmeEnvironment (base name: "acme_environment")', function() {
      // uncomment below and update the code to test the property acmeEnvironment
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property challengeType (base name: "challenge_type")', function() {
      // uncomment below and update the code to test the property challengeType
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property dnsTargetName (base name: "dns_target_name")', function() {
      // uncomment below and update the code to test the property dnsTargetName
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property dnsTargetType (base name: "dns_target_type")', function() {
      // uncomment below and update the code to test the property dnsTargetType
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property eabHmacKey (base name: "eab_hmac_key")', function() {
      // uncomment below and update the code to test the property eabHmacKey
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property eabKeyId (base name: "eab_key_id")', function() {
      // uncomment below and update the code to test the property eabKeyId
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property gcpProject (base name: "gcp_project")', function() {
      // uncomment below and update the code to test the property gcpProject
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property hostedZone (base name: "hosted_zone")', function() {
      // uncomment below and update the code to test the property hostedZone
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property resourceGroup (base name: "resource_group")', function() {
      // uncomment below and update the code to test the property resourceGroup
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

    it('should have the property timeout (base name: "timeout")', function() {
      // uncomment below and update the code to test the property timeout
      //var instance = new akeyless.GoogleTrustTargetDetails();
      //expect(instance).to.be();
    });

  });

}));
