/**
 * Akeyless API
 * The purpose of this application is to provide access to Akeyless API.
 *
 * The version of the OpenAPI document: 3.0
 * Contact: support@akeyless.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.akeyless);
  }
}(this, function(expect, akeyless) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new akeyless.PolicyOutput();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PolicyOutput', function() {
    it('should create an instance of PolicyOutput', function() {
      // uncomment below and update the code to test PolicyOutput
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be.a(akeyless.PolicyOutput);
    });

    it('should have the property accountId (base name: "account_id")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property allowedAlgorithms (base name: "allowed_algorithms")', function() {
      // uncomment below and update the code to test the property allowedAlgorithms
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property allowedKeyNames (base name: "allowed_key_names")', function() {
      // uncomment below and update the code to test the property allowedKeyNames
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property allowedKeyTypes (base name: "allowed_key_types")', function() {
      // uncomment below and update the code to test the property allowedKeyTypes
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property maxRotationIntervalDays (base name: "max_rotation_interval_days")', function() {
      // uncomment below and update the code to test the property maxRotationIntervalDays
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property objectTypes (base name: "object_types")', function() {
      // uncomment below and update the code to test the property objectTypes
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new akeyless.PolicyOutput();
      //expect(instance).to.be();
    });

  });

}));
